ELIMINACIÓN GAUSSIANA

In [9]:
#Escriba un código de eliminación Gaussiana para resolver el sistema Ax=B.

import numpy as np
N=np.random.randint(3, 7)
Arreglo=(np.random.random((N,N))*10.0)-5.0
B=(np.random.random((N,1))*10.0)-5.0


print(N)
print(Arreglo)
#compare sus resultados con el paquete de numpy:
#https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

3
[[-2.37202355  4.31809672  3.20787315]
 [ 3.13234495  4.5400256  -2.62212555]
 [ 4.24557832  3.30454817 -4.53301239]]
