ELIMINACIÓN GAUSSIANA

In [89]:
#Escriba un código de eliminación Gaussiana para resolver el sistema Ax=B.

import numpy as np
N=np.random.randint(3, 7)
Arreglo=(np.random.random((N,N))*10.0)-5.0
B=(np.random.random((N,1))*10.0)-5.0

print(N)

#print(Arreglo)
#print(B)

mat_amp = np.hstack((Arreglo,B))

print(mat_amp)
#compare sus resultados con el paquete de numpy:
#https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

3
[[ 0.93814658  2.50575297 -3.28957196 -3.7848848 ]
 [-4.57291666 -2.97894353  1.07754205  1.63127059]
 [-2.16014178  4.84222451 -2.85823318 -3.99645283]]


In [124]:
mat_gauss = np.copy(mat_amp)

print("Matriz Original:")
print(mat_amp)

for j in range(N):
    mat_gauss[j] = mat_gauss[j]/mat_gauss[j,j]
    print("\nMatriz Triangular Superior (Procediendo...):")
    print(np.round(mat_gauss, 2))
    for i in range(j+1, N):
        mat_gauss[i] = mat_gauss[i] - mat_gauss[i,j] * mat_gauss[j]

print("Matriz Original:")
print(mat_amp)
print("\nMatriz Triangular Superior (Resultado):")
print(np.round(mat_gauss, 2))


Matriz Original:
[[ 0.93814658  2.50575297 -3.28957196 -3.7848848 ]
 [-4.57291666 -2.97894353  1.07754205  1.63127059]
 [-2.16014178  4.84222451 -2.85823318 -3.99645283]]

Matriz Triangular Superior (Procediendo...):
[[ 1.    2.67 -3.51 -4.03]
 [-4.57 -2.98  1.08  1.63]
 [-2.16  4.84 -2.86 -4.  ]]

Matriz Triangular Superior (Procediendo...):
[[  1.     2.67  -3.51  -4.03]
 [  0.     1.    -1.62  -1.82]
 [  0.    10.61 -10.43 -12.71]]

Matriz Triangular Superior (Procediendo...):
[[ 1.    2.67 -3.51 -4.03]
 [ 0.    1.   -1.62 -1.82]
 [ 0.    0.    1.    0.98]]
Matriz Original:
[[ 0.93814658  2.50575297 -3.28957196 -3.7848848 ]
 [-4.57291666 -2.97894353  1.07754205  1.63127059]
 [-2.16014178  4.84222451 -2.85823318 -3.99645283]]

Matriz Triangular Superior (Resultado):
[[ 1.    2.67 -3.51 -4.03]
 [ 0.    1.   -1.62 -1.82]
 [ 0.    0.    1.    0.98]]


In [130]:
#Resolviendo hacia atrás

x = mat_gauss[0,N]



print(f"x = {np.round(x,2)}")

x = -4.03
