ELIMINACIÓN GAUSSIANA

In [3]:
#Escriba un código de eliminación Gaussiana para resolver el sistema Ax=B.

import numpy as np
N=np.random.randint(3, 7)
Arreglo=(np.random.random((N,N))*10.0)-5.0
B=(np.random.random((N,1))*10.0)-5.0

print(N)

#print(Arreglo)
#print(B)

mat_amp = np.hstack((Arreglo,B))

print(mat_amp)
#compare sus resultados con el paquete de numpy:
#https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

5
[[-3.71898321  3.83528391 -0.55879089 -4.74508178  1.95143788  1.82362656]
 [-3.26917583  4.70824373  4.62310943 -3.61860929 -4.54003578  2.54834981]
 [ 0.82733434  1.20667939 -3.60839743  2.11469184  0.19039167 -1.23134004]
 [ 3.81878825  1.89690591 -3.4239749  -4.44302741 -4.72717838  3.15352183]
 [-2.08273852 -2.58056426 -1.08239575 -0.61605403 -0.96018135  2.26328978]]


In [4]:
mat_gauss = np.copy(mat_amp)

print("Matriz Original:")
print(mat_amp)

for j in range(N): #Eliminación Gaussiana
    mat_gauss[j] = mat_gauss[j]/mat_gauss[j,j]
    print("\nMatriz Triangular Superior (Procediendo...):")
    print(np.round(mat_gauss, 2))
    for i in range(j+1, N):
        mat_gauss[i] = mat_gauss[i] - mat_gauss[i,j] * mat_gauss[j]

print("Matriz Original:")
print(mat_amp)
print("\nMatriz Triangular Superior (Resultado):")
print(np.round(mat_gauss, 2))

Matriz Original:
[[-3.71898321  3.83528391 -0.55879089 -4.74508178  1.95143788  1.82362656]
 [-3.26917583  4.70824373  4.62310943 -3.61860929 -4.54003578  2.54834981]
 [ 0.82733434  1.20667939 -3.60839743  2.11469184  0.19039167 -1.23134004]
 [ 3.81878825  1.89690591 -3.4239749  -4.44302741 -4.72717838  3.15352183]
 [-2.08273852 -2.58056426 -1.08239575 -0.61605403 -0.96018135  2.26328978]]

Matriz Triangular Superior (Procediendo...):
[[ 1.   -1.03  0.15  1.28 -0.52 -0.49]
 [-3.27  4.71  4.62 -3.62 -4.54  2.55]
 [ 0.83  1.21 -3.61  2.11  0.19 -1.23]
 [ 3.82  1.9  -3.42 -4.44 -4.73  3.15]
 [-2.08 -2.58 -1.08 -0.62 -0.96  2.26]]

Matriz Triangular Superior (Procediendo...):
[[ 1.   -1.03  0.15  1.28 -0.52 -0.49]
 [ 0.    1.    3.83  0.41 -4.68  0.71]
 [ 0.    2.06 -3.73  1.06  0.62 -0.83]
 [ 0.    5.84 -4.   -9.32 -2.72  5.03]
 [ 0.   -4.73 -0.77  2.04 -2.05  1.24]]

Matriz Triangular Superior (Procediendo...):
[[ 1.000e+00 -1.030e+00  1.500e-01  1.280e+00 -5.200e-01 -4.900e-01]
 [ 0.000

In [9]:
#Resolviendo hacia atrás

solucion = np.zeros(N)

for i in range(N - 1, -1, -1):
    solucion[i] = mat_gauss[i,-1] - np.dot(mat_gauss[i, i+1:N], solucion[i+1:N])
    print(np.round(solucion,2))

print(f"x = {np.round(solucion,2)}")

[ 0.   0.   0.   0.  -0.4]
[ 0.    0.    0.   -0.54 -0.4 ]
[ 0.    0.   -0.16 -0.54 -0.4 ]
[ 0.   -0.3  -0.16 -0.54 -0.4 ]
[-0.29 -0.3  -0.16 -0.54 -0.4 ]
x = [-0.29 -0.3  -0.16 -0.54 -0.4 ]


In [ ]:
# --- Verificación Final ---

print("\n--- Comparación de Resultados ---")

print(f"Mi solución:  {np.round(solucion, 6)}")

solucion_numpy = np.linalg.solve(Arreglo, B.flatten())
print(f"Solución de NumPy: {np.round(solucion_numpy, 6)}")

# Verificación automática
es_correcta = np.allclose(solucion, solucion_numpy) #numpy.allclose compara los valores de un arreglo
                                                    #con otro con una tolerancia por defecto de 1x10^-5
print(f"\n¿Mi implementación es correcta? ->", "Sí" if {es_correcta} else "No")


--- Comparación de Resultados ---
Mi solución:  [-0.290828 -0.297828 -0.162734 -0.540619 -0.395564]
Solución de NumPy: [-0.290828 -0.297828 -0.162734 -0.540619 -0.395564]

¿Mi implementación es correcta? -> Sí
