# Principal Component Analysis (PCA)

In [2]:
import numpy as np
import matplotlib.pylab as plt

EJERCICIO 1

$$Cov_{u,v} = Cov_{v,u} = \frac{\sum_{i=1}^n (u_i-\bar{u})(v_i-\bar{v})}{n-1}$$
$$Var_u = \frac{\sum_{i=1}^n (u_i-\bar{u})^2}{n-1}$$
$$Var_v = \frac{\sum_{i=1}^n (v_i-\bar{v})^2}{n-1}$$

In [20]:

#Ejercicio 1:
# Los arrays `u` y `v` representan dos series en función del tiempo `t`.
# 1) Grafique las dos series de datos en una misma imagen y guarde dicha gráfica sn mostrarla en 'serie.pdf'
# 2) Calcule la covarianza entre `u` y `v` e imprima su valor.
# 3) Calcule la varianza de `u` e imprima su valor.
# 4) Imprima un mensaje donde explique qué puede inferir del valor de covarianza obtenido.
import numpy as np
t = np.array([0.,0.1,0.2,0.3,0.4,0.5,0.6, 0.8, 0.9])
u = np.array([-12.,-45.,-6.,-78.,-34.,-22.,10.,-31.,27.])
v = np.array([3.,11.,1.3,37.,11.,6.,-23.,7.,7.])

# 1)
plt.plot(t,u, label="Serie u")
plt.plot(t,v, label="Serie v")
plt.savefig("serie.pdf")
plt.close()

# 2)
#u_med = u.mean()
#v_med = v.mean()
#print(v_med)
#u_centrado = u - u.mean()
#v_centrado = v - v.mean()
cov = np.sum((u - u.mean())*(v - v.mean()))/(np.size(u)-1)
print(f"Covarianza 'a mano': {cov}")

# 3)
var_u = np.sum((u - u.mean())**2)/(np.size(u)-1)
print(f"Var_u = {var_u}")

# 4)
print(f"El valor de covarianza negativo ({cov}) indica que existe una correlación inversa entre las series u y v."
      + "\n\tEsto significa que, en general, cuando los valores de u aumentan, los valores de v tienden a disminuir, y viceversa."
      + "\n\tEsta relación se puede observar visualmente en la gráfica.")

# 5) Construya un código para obtener la matriz de covarianza de los datos anteriores. (compare su resultado con el de numpy.cov)
var_v = np.sum((v - v.mean())**2)/(np.size(v)-1)
matriz_cov = np.array([[var_u,cov],[cov,var_v]])
print(f"\nMatriz de covarianza 'a mano':\n\n{matriz_cov}\n")

print(f"Matriz de covarianza por numpy:\n\n{np.cov(u,v)}\n")
print(f"Error relativo:\n\n{np.round(np.abs(matriz_cov-np.cov(u,v)),13)}\n")


Covarianza 'a mano': -363.6375
Var_u = 958.1944444444443
El valor de covarianza negativo (-363.6375) indica que existe una correlación inversa entre las series u y v.
	Esto significa que, en general, cuando los valores de u aumentan, los valores de v tienden a disminuir, y viceversa.
	Esta relación se puede observar visualmente en la gráfica.

Matriz de covarianza 'a mano':

[[ 958.19444444 -363.6375    ]
 [-363.6375      235.085     ]]

Matriz de covarianza por numpy:

[[ 958.19444444 -363.6375    ]
 [-363.6375      235.085     ]]

Error relativo:

[[1.e-13 0.e+00]
 [0.e+00 0.e+00]]



EJERCICIO 2:

In [43]:
# 6) Repita lo anterior para obtener la matriz de covarianza de los datos del archivo: room-temperature.csv
import pandas as pd

datos_temp = pd.read_csv("room-temperature.csv", index_col='Date')

datos_numericos = datos_temp.values
tiempo = datos_temp.index

matriz_cov_temp = np.cov(datos_numericos, rowvar=False)
print(matriz_cov_temp)
# 6a) Grafique las 4 series de datos en una misma imagen y guarde dicha gráfica sin mostrarla en 'serieTemp.pdf'

datos_temp.plot(figsize=(12, 6))
plt.xlabel("Fecha y hora")
plt.ylabel("Temperatura (K)")
plt.savefig("serieTemp.pdf")
plt.close()

# 7) Calcule los autovalores y los autovectores de la matriz de covarianza de los datos de temperatura.
#(use el paquete: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)

# 8) Lea: https://towardsdatascience.com/a-one-stop-shop-for-principal-component-analysis-5582fb7e0a9c
#Organice sus autovalores y autovectores e imprima cuales son sus componentes principales (puede usar paquetes de numpy para encontrar autovalores y autovectores. lea cuidadosamente la documentación.)
# 9) Imprima cuantos componentes principales considera que son necesarios para explicar sus datos.
# 10) Grafique sus datos en el nuevo sistema de referencia (PC1 PC2)
# 11) Comente cuales son las agrupaciones de sus variables originales que aparecen. Mire en su gráfica de los datos originales si el resultado tiene sentido.


[[2.70448669 2.4044663  1.45784091 1.64101544]
 [2.4044663  2.94163122 1.60030594 1.80590181]
 [1.45784091 1.60030594 2.52082168 2.31242133]
 [1.64101544 1.80590181 2.31242133 2.71436626]]


EJERCICIO 3:

In [ ]:
# 12) Repita lo anterior para obtener la matriz de covarianza de los datos del archivo: WCBD.dat

# 13) Calcule los autovalores y los autovectores de la matriz de covarianza de los datos.
#(use el paquete: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html)

# 14) Lea: https://towardsdatascience.com/a-one-stop-shop-for-principal-component-analysis-5582fb7e0a9c
#Organice sus autovalores y autovectores e imprima cuales son sus componentes principales (puede usar paquetes de numpy para encontrar autovalores y autovectores. lea cuidadosamente la documentación.)

# 15) Imprima cuantos componentes principales considera que son necesarios para explicar sus datos.

# 16) Grafique sus datos en el nuevo sistema de referencia (PC1 PC2)

# 17) Puede ver agrupaciones entre los tumores malignos y benignos?



RECUERDE LOS PASOS:

descargar y limpiar los datos. Ampliarlos (si aplica)

restarles el promedio y normalizar (si aplica)

Calcular la matriz de covarianza de los datos

Encontrar autovalores y autovectores (usar paquete de numpy), y organizarlos (de mayor a menor autovalor)

Mirar los autovalores y decidir cuántos componentes principales (autovectores) mantener.

